### ISSUE TITLE
EXCEPTION

### ISSUE THREAD

**Issue by pintofran** [Santax01/Parciales-PdeP#1]
Generalmente en estos casos se espera una Exception si no se puede realizar la operacion. Un else vacio nunca es buena señal.

https://github.com/Santax01/Parciales-PdeP/blob/ee838edd4dd56b1d9a89a5a47b4943f18b61fa35/ElAsadito/src/Asado.wlk#L16-L21

**Comment by SantiBoero1** [comment]
Perfecto, agregue la exception en el else
