### ISSUE TITLE
Encapsulamiento

### ISSUE THREAD

**Issue by pintofran** [Santax01/Parciales-PdeP#2]
`elementosCerca().first()` deberia ser responsabilidad de la persona 

https://github.com/Santax01/Parciales-PdeP/blob/ee838edd4dd56b1d9a89a5a47b4943f18b61fa35/ElAsadito/src/Criterios.wlk#L6

**Comment by SantiBoero1** [comment]
Lo arregle declarando un metodo en persona que sea primerElementoCerca
