### ISSUE TITLE
Efecto

### ISSUE THREAD

**Issue by pintofran** [Santax01/Parciales-PdeP#3]
Esto no parece estar teniendo ningun efecto sobre la persona
https://github.com/Santax01/Parciales-PdeP/blob/ee838edd4dd56b1d9a89a5a47b4943f18b61fa35/ElAsadito/src/Criterios.wlk#L14

**Comment by SantiBoero1** [comment]
Si, recien lo note, Ahora cree un metodo "aniadirElementosCerca(unosElementos)" y en persona se añaden todos a su lista
