### ISSUE TITLE
Suposicion

### ISSUE THREAD

**Issue by pintofran** [Santax01/Parciales-PdeP#4]
Habria que preguntarlo en el parcial. Yo supongo que no se van a llevar todo lo que tenian cerca..
https://github.com/Santax01/Parciales-PdeP/blob/ee838edd4dd56b1d9a89a5a47b4943f18b61fa35/Dudas%20parcial%20asado.txt#L5-L6

**Comment by SantiBoero1** [comment]
Perfecto, lo dejo como lo resolvi en ese caso
