### ISSUE TITLE
Alternado

### ISSUE THREAD

**Issue by pintofran** [Santax01/Parciales-PdeP#5]
Para que algo sea alternado vas a tener que pensar en estado. Uno puede alternar una forma de actuar solamente si se acuerda de lo que hizo anteriormente. Pensalo ;)
https://github.com/Santax01/Parciales-PdeP/blob/ee838edd4dd56b1d9a89a5a47b4943f18b61fa35/Dudas%20parcial%20asado.txt#L10

**Comment by SantiBoero1** [comment]
`class Alternado {
	var quieroComer
	
	method decideComer(unaComida){
		quieroComer = !quieroComer
		return quieroComer
	}
	
}`

Lo hice de esta forma, a diferencia de los demas lo hice clase, por la variable quieroComer, ya que no puedo inicializarla (por falta de datos) y porque sino todos los que coman y tenga el gusto alternado compartirian el mismo valor
